name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-for-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Add targets
      run: |
        rustup target add aarch64-apple-darwin
        rustup target add x86_64-apple-darwin
    - name: Build
      run: cargo build --target x86_64-apple-darwin --target aarch64-apple-darwin
    - name: Run tests
      run: cargo test
  build-for-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test

